FortreeJungle_MapScripts::
	.byte 0

FortreeJungle_EventScript_Zarude::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_ZARUDE, CRY_MODE_NORMAL
	msgbox FortreeJungle_Zarude, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Zarude:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Zarude: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Garrruwl!$"

FortreeJungle_EventScript_Oranguru::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_ORANGURU, CRY_MODE_NORMAL
	msgbox FortreeJungle_Oranguru, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Oranguru:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Oranguru: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Guuuuro?$"

FortreeJungle_EventScript_Pansage::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PANSAGE, CRY_MODE_NORMAL
	msgbox FortreeJungle_Pansage, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Pansage:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Pansage: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Papaseg?$"

FortreeJungle_EventScript_Simisage::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SIMISAGE, CRY_MODE_NORMAL
	msgbox FortreeJungle_Simisage, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Simisage:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Simisage: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Seeemisag!$"

FortreeJungle_EventScript_Pansear::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PANSEAR, CRY_MODE_NORMAL
	msgbox FortreeJungle_Pansear, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Pansear:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Pansear: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Papaserr!$"

FortreeJungle_EventScript_Simisear::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SIMISEAR, CRY_MODE_NORMAL
	msgbox FortreeJungle_Simisear, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Simisear:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Simisear: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Seeemiserrr!$"

FortreeJungle_EventScript_Panpour::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PANPOUR, CRY_MODE_NORMAL
	msgbox FortreeJungle_Panpour, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Panpour:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Panpour: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Papapur!$"

FortreeJungle_EventScript_Simipour::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SIMIPOUR, CRY_MODE_NORMAL
	msgbox FortreeJungle_Simipour, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Simipour:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Simipour: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Seeemipuur?$"

FortreeJungle_EventScript_Heracross::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_HERACROSS, CRY_MODE_NORMAL
	msgbox FortreeJungle_Heracross, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Heracross:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Heracross: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Herriac!$"

FortreeJungle_EventScript_Pinsir::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PINSIR, CRY_MODE_NORMAL
	msgbox FortreeJungle_Pinsir, MSGBOX_DEFAULT
	waitmoncry
	release
	end

FortreeJungle_Pinsir:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Pinsir: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pininsiir!$"

