#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT)\
    F(DISARMING_VOICE)\
    F(SNARL)\
    F(SCALD)\
    F(SUPERCELL_SLAM)\
    F(DRAINING_KISS)\
    F(TEMPER_FLARE)\
    F(SMART_STRIKE)\
    F(DRAIN_PUNCH)\
    F(STEALTH_ROCK)\
    F(PSYCHIC_NOISE)\
    F(SHADOW_CLAW)\
    F(PLAY_ROUGH)\
    F(DRAGON_DANCE)\
    F(MAGICAL_LEAF)\
    F(U_TURN)\
    F(WEATHER_BALL)\
    F(ICICLE_SPEAR)\
    F(DARK_PULSE)\
    F(TRAILBLAZE)\
    F(UPPER_HAND)\
    F(LIQUIDATION)\
    F(ELECTRIC_TERRAIN)\
    F(GRASSY_TERRAIN)\
    F(PSYCHIC_TERRAIN)\
    F(MISTY_TERRAIN)\
    F(LEECH_LIFE)\
    F(AURA_SPHERE)\
    F(SCALE_SHOT)\
    F(BURNING_JEALOUSY)\
    F(METEOR_BEAM)\
    F(SCORCHING_SANDS)\
    F(PHANTOM_FORCE)\
    F(ICE_SPINNER)\
    F(SKITTER_SMACK)\
    F(EXPANDING_FORCE)\
    F(GRASSY_GLIDE)\
    F(DAZZLING_GLEAM)\
    F(DUAL_WINGBEAT)\
    F(SWORDS_DANCE)\
    F(HEAVY_SLAM)\
    F(MISTY_EXPLOSION)\
    F(AVALANCHE)\
    F(WILL_O_WISP)\
    F(AIR_CUTTER)\
    F(TRIPLE_AXEL)\
    F(FLIP_TURN)\
    F(POISON_JAB)\
    F(ACID_SPRAY)\
    F(VOLT_SWITCH)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
