Rustboro_Farms_MapScripts::
	.byte 0

RustboroFarms_EventScript_Mudsdale::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MUDSDALE, CRY_MODE_NORMAL
	msgbox RustboroFarms_Mudsdale, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Mudsdale:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mudsdale: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Neiiigdal!!$"

RustboroFarms_EventScript_Mudbray1::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MUDBRAY, CRY_MODE_NORMAL
	msgbox RustboroFarms_Mudbray1, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Mudbray1:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mudbray: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mudeighhh?$"

RustboroFarms_EventScript_Mudbray2::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MUDBRAY, CRY_MODE_NORMAL
	msgbox RustboroFarms_Mudbray2, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Mudbray2:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mudbray: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Brayyyiiie.$"

RustboroFarms_EventScript_Mareep1::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MAREEP, CRY_MODE_NORMAL
	msgbox RustboroFarms_Mareep1, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Mareep1:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mareep: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Baaaareep!!!$"

RustboroFarms_EventScript_Mareep2::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MAREEP, CRY_MODE_NORMAL
	msgbox RustboroFarms_Mareep2, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Mareep2:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mareep: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Maraaaaeep!!!.$"

RustboroFarms_EventScript_Herdier::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_HERDIER, CRY_MODE_NORMAL
	msgbox RustboroFarms_Herdier, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Herdier:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Herdier: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ruuufffier!\p"
	.string "The {COLOR GREEN}{SHADOW LIGHT_GREEN}Herdier {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}is barking at the {COLOR GREEN}{SHADOW LIGHT_GREEN}Mareep {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}.$"

RustboroFarms_EventScript_Houndour::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_HOUNDOUR, CRY_MODE_NORMAL
	msgbox RustboroFarms_Houndour, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Houndour:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Houndour: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}DUUAR!!! HAUND!$"

RustboroFarms_EventScript_Miltank::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MILTANK, CRY_MODE_NORMAL
	msgbox RustboroFarms_Miltank, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Miltank:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Miltank: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mil Milll!$"

RustboroFarms_EventScript_Herdier1::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_HERDIER, CRY_MODE_NORMAL
	msgbox RustboroFarms_Herdier1, MSGBOX_DEFAULT
	waitmoncry
	release
	end

RustboroFarms_Herdier1:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Herdier: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Herrruff!$"






