Underwater_Route128_MapScripts::
	.byte 0

Route128_EventScript_FINIZEN::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_FINIZEN, CRY_MODE_NORMAL
	msgbox Route128_FINIZEN, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_FINIZEN:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Finizen: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Fiiiinzi!$"

Route128_EventScript_Corsola::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_CORSOLA, CRY_MODE_NORMAL
	msgbox Route128_Corsola, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Corsola:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Corsola: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Cooorsol$"

Route128_EventScript_Lanturn::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_LANTURN, CRY_MODE_NORMAL
	msgbox Route128_Lanturn, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Lanturn:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Lanturn: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Laant!!$"

Route128_EventScript_Phione::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PHIONE, CRY_MODE_NORMAL
	msgbox Route128_Phione, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Phione:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Phione: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Phoooie?$"

Route128_EventScript_Staryu::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_STARYU, CRY_MODE_NORMAL
	msgbox Route128_Staryu, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Staryu:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Staryu: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Btttzyu?$"

Route128_EventScript_Wugtrio::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_WUGTRIO, CRY_MODE_NORMAL
	msgbox Route128_Wugtrio, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Wugtrio:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Wugtrio: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Wugugug.$"

Route128_EventScript_Wishiwashi::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_WISHIWASHI, CRY_MODE_NORMAL
	msgbox Route128_Wishiwashi, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Wishiwashi:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Wishiwashi: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}W-W-wishi...$"

Route128_EventScript_Clawitzer::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_CLAWITZER, CRY_MODE_NORMAL
	msgbox Route128_Clawitzer, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Clawitzer:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Clawitzer: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Clwaaitz!$"

Route128_EventScript_Mantine::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MANTINE, CRY_MODE_NORMAL
	msgbox Route128_Mantine, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Mantine:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mantine: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tutututine!$"

Route128_EventScript_Binacle::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_BINACLE, CRY_MODE_NORMAL
	msgbox Route128_Binacle, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Binacle:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Binacle: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tutututine!$"

Route128_EventScript_Lumineon::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_LUMINEON, CRY_MODE_NORMAL
	msgbox Route128_Lumineon, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Lumineon:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Lumineon: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Luuuumi!$"

Route128_EventScript_Gyarados::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_GYARADOS, CRY_MODE_NORMAL
	msgbox Route128_Gyarados, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Gyarados:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Gyarados: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GRYYYYAR!!$"

Route128_EventScript_Octillery::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_OCTILLERY, CRY_MODE_NORMAL
	msgbox Route128_Octillery, MSGBOX_DEFAULT
	waitmoncry
	release
	end

Route128_Octillery:
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}Octillery: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Octoctoil?$"


