PastSafeHouse_MapScripts::
	.byte 0

PastSaferoom_EventScript_Portalman::
	msgbox PastSaferoom_Portalman, MSGBOX_NPC
	end

PastSaferoom_Portalman:

    .string "Return back through here to return to\n"
	.string "the present! Be safe out there!$"

PastSaferoom_EventScript_Scientist1::
	msgbox PastSaferoom_Scientist1, MSGBOX_NPC
	end

PastSaferoom_Scientist1:

    .string "We are yet to be detected here in what\n"
	.string "will eventually become Shoal Cave.\p"
	.string "It eventually breaks off of Mossdeep\n"
	.string "and drifts up north.$"

PastSaferoom_EventScript_Scientist2::
	msgbox PastSaferoom_Scientist2, MSGBOX_NPC
	end

PastSaferoom_Scientist2:
    .string "Dammit! That brat from Uva Academy\n"
	.string "isn't replying! Blast President\l"
	.string "Stone thinking we could trust a\l"
	.string "fresh out of school kid!$"

PastSaferoom_EventScript_Scientist3::
	msgbox PastSaferoom_Scientist3, MSGBOX_NPC
	end

PastSaferoom_Scientist3:
    .string "We're roughly 200 million years\n"
	.string "into the past.\p"
	.string "Id avoid going near the lilycove\n"
	.string "area. Atop of what we believe is\l"
	.string "Mt.Pyre, a Pokemon known as\l"
	.string "{COLOR GREEN}{SHADOW LIGHT_GREEN}The Winged King {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}lives up there.$"

