Floor1Subbit_MapScripts::
	.byte 0

Subbit_EventScript_Chase::
	msgbox Subbit_Chase, MSGBOX_NPC
	end

Subbit_EventScript_Nony::
	msgbox Subbit_Nony, MSGBOX_NPC
	end

Subbit_EventScript_Tadashi::
	msgbox Subbit_Tadashi, MSGBOX_NPC
	end

Subbit_EventScript_Mattando::
	msgbox Subbit_Mattando, MSGBOX_NPC
	end

Subbit_EventScript_JoeOwlArt::
	msgbox Subbit_JoeOwlArt, MSGBOX_NPC
	end

Subbit_Chase:
	.string "{COLOR RED}{SHADOW LIGHT_RED}OhLyon: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}What? Have you never talked\n"
	.string "with a talking Wingull before?$"

Subbit_Nony:
	.string "{COLOR RED}{SHADOW LIGHT_RED}Nony: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm open to sponsorship chances\n"
	.string "for yarn & art supplies!$"

Subbit_Tadashi:
	.string "{COLOR RED}{SHADOW LIGHT_RED}Tadashi: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Don't sweat the petty things\n"
	.string "and don't pet the sweaty things!$"

Subbit_Mattando:
	.string "{COLOR RED}{SHADOW LIGHT_RED}Matt: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This song is for you, Latias.$"

Subbit_JoeOwlArt:
	.string "{COLOR RED}{SHADOW LIGHT_RED}JoeOwlArt: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}O.O$"




	